### ISSUE TITLE
prototype selection benchmark

### ISSUE THREAD

**Issue by sjanssen2** [biocore/genome-subsampler#14]
are we ready for a 1 million genome tree?
Runtime, Memory?, Accuracy with #genomes and #selected genomes

**Comment by sjanssen2** [comment]
Can we simulate distance matrices where we know the best prototypes?
Low noise background for total matrix + high noise for prototypes?!

**Comment by sjanssen2** [comment]
@wasade any idea if skbio distance matrix objects are able to load a 1m x 1m matrix into memory?

**Comment by qiyunzhu** [comment]
@sjanssen2 If the prototypes mean genomes, I believe we can. Just do MinHash. But maybe you meant something else?

**Comment by sjanssen2** [comment]
I think this issue has been addressed. Benchmarking notebook is now in.
